# Site settings

# REQUIRED CHANGES
# Edit next line, providing your own name.
title: Mark Cummins | Professional Portfolio
# Edit next line, replacing 'techfolios' with your github username
url: "https://markrcummins.github.io"
# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: ""

# OPTIONAL CHANGES
# You might want to change the bio page label to something else, such as CV
bio-page-label: Resume
# You might want to change the theme associated with one or more sections of the site.
# Defining your own custom theme variations is easy. See the documentation.
theme-home: theme-home-builtin-custom.html
theme-projects: theme-projects-builtin-custom.html
theme-essays: theme-essays-builtin-custom.html
theme-bio: theme-bio-builtin-1.html
# YOU NORMALLY NEVER CHANGE THE FOLLOWING
markdown: kramdown
include: [_data]

